NixOS: fix missing library errors when running libservo tests (#42835)
on NixOS, under X11 at least, many libservo tests panic:

```
$ ./mach test-unit -p libservo test_create_webview
[...]
    thread 'test_create_webview' (3589026) panicked at /home/delan/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/wayland-sys-0.31.8/src/client.rs:110:103:
    Library libwayland-client.so could not be loaded.
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

this patch fixes that by adding `wayland` to the LD_LIBRARY_PATH in
shell.nix.

Testing: tested manually as above

Signed-off-by: delan azabani <dazabani@igalia.com>